//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceapp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IgetNumbers")]
    public interface IgetNumbers {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:getNumbersIntf-IgetNumbers) of message getLottoNumbersRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getNumbersIntf-IgetNumbers#getLottoNumbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceapp.ServiceReference1.getLottoNumbersResponse getLottoNumbers(WebServiceapp.ServiceReference1.getLottoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLottoNumbers", WrapperNamespace="urn:getNumbersIntf-IgetNumbers", IsWrapped=true)]
    public partial class getLottoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Min;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Max;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int Numbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int count;
        
        public getLottoNumbersRequest() {
        }
        
        public getLottoNumbersRequest(int Min, int Max, int Numbers, int count) {
            this.Min = Min;
            this.Max = Max;
            this.Numbers = Numbers;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLottoNumbersResponse", WrapperNamespace="urn:getNumbersIntf-IgetNumbers", IsWrapped=true)]
    public partial class getLottoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getLottoNumbersResponse() {
        }
        
        public getLottoNumbersResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IgetNumbersChannel : WebServiceapp.ServiceReference1.IgetNumbers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IgetNumbersClient : System.ServiceModel.ClientBase<WebServiceapp.ServiceReference1.IgetNumbers>, WebServiceapp.ServiceReference1.IgetNumbers {
        
        public IgetNumbersClient() {
        }
        
        public IgetNumbersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IgetNumbersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgetNumbersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgetNumbersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceapp.ServiceReference1.getLottoNumbersResponse WebServiceapp.ServiceReference1.IgetNumbers.getLottoNumbers(WebServiceapp.ServiceReference1.getLottoNumbersRequest request) {
            return base.Channel.getLottoNumbers(request);
        }
        
        public string getLottoNumbers(int Min, int Max, int Numbers, int count) {
            WebServiceapp.ServiceReference1.getLottoNumbersRequest inValue = new WebServiceapp.ServiceReference1.getLottoNumbersRequest();
            inValue.Min = Min;
            inValue.Max = Max;
            inValue.Numbers = Numbers;
            inValue.count = count;
            WebServiceapp.ServiceReference1.getLottoNumbersResponse retVal = ((WebServiceapp.ServiceReference1.IgetNumbers)(this)).getLottoNumbers(inValue);
            return retVal.@return;
        }
    }
}
