//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "Clientes1Table1", "Clientes1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Identity_Framework_Linq.Clientes1), "Table1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Identity_Framework_Linq.Table1))]

#endregion

namespace Identity_Framework_Linq
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes1> Clientes1Set
        {
            get
            {
                if ((_Clientes1Set == null))
                {
                    _Clientes1Set = base.CreateObjectSet<Clientes1>("Clientes1Set");
                }
                return _Clientes1Set;
            }
        }
        private ObjectSet<Clientes1> _Clientes1Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Table1> Table1Set
        {
            get
            {
                if ((_Table1Set == null))
                {
                    _Table1Set = base.CreateObjectSet<Table1>("Table1Set");
                }
                return _Table1Set;
            }
        }
        private ObjectSet<Table1> _Table1Set;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes1Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes1Set(Clientes1 clientes1)
        {
            base.AddObject("Clientes1Set", clientes1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Table1Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTable1Set(Table1 table1)
        {
            base.AddObject("Table1Set", table1);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Clientes1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes1 object.
        /// </summary>
        /// <param name="idclientes">Initial value of the Idclientes property.</param>
        public static Clientes1 CreateClientes1(global::System.Int32 idclientes)
        {
            Clientes1 clientes1 = new Clientes1();
            clientes1.Idclientes = idclientes;
            return clientes1;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Idclientes
        {
            get
            {
                return _Idclientes;
            }
            set
            {
                if (_Idclientes != value)
                {
                    OnIdclientesChanging(value);
                    ReportPropertyChanging("Idclientes");
                    _Idclientes = StructuralObject.SetValidValue(value, "Idclientes");
                    ReportPropertyChanged("Idclientes");
                    OnIdclientesChanged();
                }
            }
        }
        private global::System.Int32 _Idclientes;
        partial void OnIdclientesChanging(global::System.Int32 value);
        partial void OnIdclientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, true, "Apellidos");
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true, "Ciudad");
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pais
        {
            get
            {
                return _Pais;
            }
            set
            {
                OnPaisChanging(value);
                ReportPropertyChanging("Pais");
                _Pais = StructuralObject.SetValidValue(value, true, "Pais");
                ReportPropertyChanged("Pais");
                OnPaisChanged();
            }
        }
        private global::System.String _Pais;
        partial void OnPaisChanging(global::System.String value);
        partial void OnPaisChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "Clientes1Table1", "Table1")]
        public EntityCollection<Table1> Table1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Table1>("Model1.Clientes1Table1", "Table1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Table1>("Model1.Clientes1Table1", "Table1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Table1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Table1 object.
        /// </summary>
        /// <param name="idclientes">Initial value of the Idclientes property.</param>
        public static Table1 CreateTable1(global::System.Int32 idclientes)
        {
            Table1 table1 = new Table1();
            table1.Idclientes = idclientes;
            return table1;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Idclientes
        {
            get
            {
                return _Idclientes;
            }
            set
            {
                if (_Idclientes != value)
                {
                    OnIdclientesChanging(value);
                    ReportPropertyChanging("Idclientes");
                    _Idclientes = StructuralObject.SetValidValue(value, "Idclientes");
                    ReportPropertyChanged("Idclientes");
                    OnIdclientesChanged();
                }
            }
        }
        private global::System.Int32 _Idclientes;
        partial void OnIdclientesChanging(global::System.Int32 value);
        partial void OnIdclientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, true, "Apellidos");
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true, "Ciudad");
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pais
        {
            get
            {
                return _Pais;
            }
            set
            {
                OnPaisChanging(value);
                ReportPropertyChanging("Pais");
                _Pais = StructuralObject.SetValidValue(value, true, "Pais");
                ReportPropertyChanged("Pais");
                OnPaisChanged();
            }
        }
        private global::System.String _Pais;
        partial void OnPaisChanging(global::System.String value);
        partial void OnPaisChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "Clientes1Table1", "Clientes1")]
        public Clientes1 Clientes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes1>("Model1.Clientes1Table1", "Clientes1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes1>("Model1.Clientes1Table1", "Clientes1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes1> Clientes1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes1>("Model1.Clientes1Table1", "Clientes1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes1>("Model1.Clientes1Table1", "Clientes1", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
